version: '3'

networks:
    app_network:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: ${APP_NAME}_nginx
        ports:
            - "8000:80"
        links:
            - php
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
            - ./docker/logs/nginx:/var/logs/nginx:rw
        depends_on:
            - php
            - mysql
        networks:
            - app_network
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ${APP_NAME}_php
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
            - postgresql
        ports:
            - "9001:9000"
        networks:
            - app_network

    mysql:
        image: mysql:latest
        container_name: ${APP_NAME}_mysql
        environment:
            MYSQL_DATABASE: your_database_name
            MYSQL_USER: your_database_user
            MYSQL_PASSWORD: your_database_password
            MYSQL_ROOT_PASSWORD: root_password
        ports:
            - "33360:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
        networks:
            - app_network

    postgresql:
        image: postgres:latest
        container_name: ${APP_NAME}_postgresql
        environment:
            POSTGRES_DB: your_postgres_database_name
            POSTGRES_USER: your_postgres_user
            POSTGRES_PASSWORD: your_postgres_password
        ports:
            - "54320:5432"
        volumes:
            - ./data/postgresql:/var/lib/postgresql/data
        networks:
            - app_network
